name: ocr_projet_pfe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6+1
  path_provider: ^2.0.13
  flutter_spinkit: ^5.1.0
  colours: ^0.0.2
  curved_navigation_bar: ^1.0.3
  shared_preferences:
  flutter_launcher_icons:
  flutter_gif: any
  http: ^0.13.5
  syncfusion_flutter_pdfviewer: ^19.0.0
  flutter_pdfview: ^1.3.1
  get_storage: ^2.1.1
  flutter_gifimage:
  validators:
  get: 4.6.5
  flutter:
    sdk: flutter
  email_validator: ^2.1.17
  dio: ^5.0.2
  smartrefresh: ^0.0.2
flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/application.png"


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/application.png
    - assets/
  fonts:
    - family: MyFont
      fonts:
        - asset: fonts/Malvie Trial.otf

